services:
  db:
    image: mysql:8.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nginx-network
      - app-network

  back:
    image: ${BACKEND_CONTAINER_REGISTERY}
    restart: always
    depends_on:
      - db
    networks:
      - nginx-network
      - app-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}
      ACCESS_JWT_SECRET: ${JWT_ACCESS_SECRET}
      REFRESH_JWT_SECRET: ${JWT_REFRESH_SECRET}
      TOKEN_TYPE: ${JWT_TOKEN_TYPE}
      CRYPTO_SECRET: ${CRYPTO_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}

  front:
    image: ${FRONTEND_CONTAINER_REGISTERY}
    restart: always
    depends_on:
      - back
    networks:
      - nginx-network
      - app-network
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
  nginx-network:
    external: true
